databases:
  - name: anime-quiz-db
    databaseName: anime_quiz
    plan: free
    ipAllowList: []

services:
  - type: web
    name: anime-quiz
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx drizzle-kit push && npx tsx src/scripts/seed.ts && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anime-quiz-db
          property: connectionString
    buildFilter:
      paths:
        - src/**/*.ts
        - src/**/*.tsx
        - package.json
        - package-lock.json
